Fix/opt out of rendering
Kentico/xperience-by-kentico-tag-manager pull request #22
Opened 2024-05-13 13:46 UTC by bkapustik

# Motivation

Disable default rendering of tags in the Xperience administration pagebuilder and preview.
Add option to select rendering in pagebuilder or preview or both.

## Checklist

- [x] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

## How to test

If manual testing is required, what are the steps?

2024-05-13 16:34 UTC, seangwright requested changes

2024-05-13 16:34 UTC, seangwright commented on src/Kentico.Xperience.TagManager/Admin/CodeSnippetConfigurationModel.cs
> +    public const string DisplayModeFormComponentOptions = $"{nameof(CodeSnippetAdministrationDisplayMode.None)};Do not dispaly in Administration\r\n" +
```suggestion
    public const string DisplayModeFormComponentOptions = $"{nameof(CodeSnippetAdministrationDisplayMode.None)};Do not display in Administration\r\n" +
```

2024-05-13 16:34 UTC, seangwright commented on src/Kentico.Xperience.TagManager/Admin/CodeSnippetConfigurationModel.cs
> +                                                $"{nameof(CodeSnippetAdministrationDisplayMode.PreviewOnly)};Display in the Preview only\r\n" +
```suggestion
                                                $"{nameof(CodeSnippetAdministrationDisplayMode.PreviewOnly)};Display in the Preview view mode only\r\n" +
```

2024-05-13 16:34 UTC, seangwright commented on src/Kentico.Xperience.TagManager/Admin/CodeSnippetConfigurationModel.cs
> +                                                $"{nameof(CodeSnippetAdministrationDisplayMode.PageBuilderOnly)};Display in the PageBuilder only\r\n" +
```suggestion
                                                $"{nameof(CodeSnippetAdministrationDisplayMode.PageBuilderOnly)};Display in the Page Builder only\r\n" +
```

2024-05-13 16:34 UTC, seangwright commented on src/Kentico.Xperience.TagManager/Admin/CodeSnippetConfigurationModel.cs
> +                                                $"{nameof(CodeSnippetAdministrationDisplayMode.Both)};Display in Preview and Pagebuilder";
```suggestion
                                                $"{nameof(CodeSnippetAdministrationDisplayMode.Both)};Display in the Preview view mode and the Page Builder";
```

2024-05-15 10:10 UTC, michalJakubis commented on src/Kentico.Xperience.TagManager/Admin/CodeSnippetConfigurationModel.cs
> +internal static class CodeSnippetExtensions
Please, move this class into separate dedicated file.

2024-05-15 10:10 UTC, michalJakubis commented on README.md
> +   - Select whether you want to display tags in the Xperience administration preview or pagebuilder, or both. This option defaults to None.
```suggestion
   - Select whether you want to display tags in the Xperience administration preview or Page Builder, or both. This option defaults to None.
```

2024-05-15 10:10 UTC, michalJakubis commented on src/Kentico.Xperience.TagManager/Rendering/DefaultChannelCodeSnippetsService.cs
> +        }
Add blank line after a closing brace.

2024-05-15 13:24 UTC, seangwright commented
@bkapustik it looks like all the suggestions I requested were reverted in [the most recent commit](https://github.com/Kentico/xperience-by-kentico-tag-manager/pull/22/commits/d25c1af8508a081d05a459466720b98da3b78a7e). Can you fix this?

2024-05-17 23:01 UTC, seangwright approved these changes

2024-05-20 08:42 UTC, merged